### PR TITLE
Fix/answerbox dropdown

### PR DESCRIPTION
**Pull request by raccube**
Screenshot 2022-02-01 at 23 57 34

🙃 Might have triggered a personal vandetta against Apple in @pixeldesu

### CODE REVIEW

**Comment by pixeldesu** [comment]
I'm working in a web agency, hating Safari is like hating Internet Explorer (it's the same browser)

**Review by pixeldesu — APPROVED** [review]

**Comment by pixeldesu** [comment]
Almost wanted to go "fix the lints", but oh well

```
$ bundle exec haml-lint app/views/answerbox/_comments.haml

1 file inspected, 0 lints detected
```

**Comment by nilsding** [comment]
Does this work with Microsoft Paint?

**Comment by pixeldesu** [comment]
Tested in Netscape Navigator

**Comment by nilsding** [comment]
Looks like massive DOG in Konquerrerr/4.2.0

**Comment by raccube** [comment]
excuse me uhhh,,, it doesn't work on my iPhone 5 running iOS 10 uh pls fixxxx zzz

**Comment by nilsding** [comment]
Please check the support matrix https://www.cisco.com/c/en/us/support/docs/switches/catalyst-6500-series-switches/69583-ptn.html

**Pull request merged**
