### PR TITLE
use .env and support SMTP configuration

### PR DESCRIPTION
**Pull request by greyidol**
Possible fix for #100. Fixes https://github.com/Retrospring/retrospring/discussions/1009.

### CODE REVIEW

**Review by pixeldesu — CHANGES_REQUESTED** [review]
Generally, the addition of configuring email via environment variables is fine.

Something we discussed internally and disagree on is the inclusion of `dotenv` in production. 

Using libraries to manipulate the environment on local machines for ease of development is fine, but in production environments, the environment should be set via deployments/`export`/systemd.

Move the `dotenv-rails` gem into the development/test group section in the Gemfile so it's only installed in those environments.

**Comment by greyidol** [comment]
Should be fixed now. I don't know if I had to do anything to update the lock file though.

**Comment by greyidol** [comment]
I just remembered, the reason I supported the production environment was to ensure that `bundle exec rails c` would work the same way as the unit as started by systemd.

**Review by pixeldesu — APPROVED** [review]

**Comment by pixeldesu** [comment]
@greyidol approved and let the lint checks run, could you move `dotenv-rails` into the alphabetically correct position so the lint passes?

**Review by raccube — APPROVED** [review]

**Pull request merged**
