### PR TITLE
Support for embedding content

### PR DESCRIPTION
**Pull request by yukimono**
Fixes Retrospring/bugs#4

screen shot 2015-04-22 at 11 38 37

### CODE REVIEW

**Comment by pixeldesu** [comment]
Could you put embeds and videos in lightboxes? So we could have smaller previews and such.

**Comment by yukimono** [comment]
For images, probably, videos is a bit more complicated. It'll probably be smart to remove gist and twitter, i need to overwrite the image filter to make it usable with lightboxes.

**Comment by yukimono** [comment]
Done.

screen shot 2015-04-22 at 0 35 03
screen shot 2015-04-22 at 0 35 06

**Comment by yukimono** [comment]
Latest addition is a "text render" for embedded images, which will open a modal when clicked.
screen shot 2015-04-28 at 10 59 35

**Pull request closed without merging**
