### PR TITLE
Add web app manifest and updated icons for PWA

### PR DESCRIPTION
**Pull request by raccube**

### CODE REVIEW

**Comment by raccube** [comment]
This is kind of blocked as we'd need to get an Apple Developer Licence as Safari doesn't provide the `PushService` API that other browsers do. Instead they have their own one which uses APN.

**Comment by nilsding** [comment]
just threw loadsamoney at , so you're no longer blocked on this

**Comment by nilsding** [comment]
maybe this gem could be of interest for this PR? https://github.com/rpush/rpush

**Comment by raccube** [comment]
Good news! Push is supported in iOS 15.4 but behind a feature flag.

**Comment by raccube** [comment]
Narrowing the scope of this PR to just PWA as adding WebPush would inflate this PR drastically.

**Review by pixeldesu — APPROVED** [review]

**Pull request merged**
